### PR TITLE
Changed '-' characters to '_' in image name

### PR DESCRIPTION
**Pull request by Creatune**
When I ran the app before making any changes, the build gave 1 error that was that the b image name was not appropriate (specifically the '-' characters). So I changed all the '-' characters to '_' and ran the app. The startup was successful, I could login. But immediately after login, the app crashed. But I am assuming this error has nothing to do with the image name or PR. This issue is addressed in #4.

### CODE REVIEW

**Comment by Creatune** [comment]
Tested, works fine.
Please let me know if there are any pending changes for this PR. If not, merge this as soon as possible :)

**Comment by srevinsaju** [comment]
Thanks @Creatune. There are some changes to some files to be removed (for example . grade files). I will remove those changes and merge soon. I am on mobile now

**Comment by Creatune** [comment]
Yeah I am aware of the unnecessary changes. Sounds good :)

**Comment by Creatune** [comment]
Lets make this app a success

**Comment by srevinsaju** [comment]
Thanks @Creatune

**Pull request merged**
